In [76]:
! pip install numpy
import numpy as np


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [77]:
# creation of numpy array
# the output is not seperated by comas 
x = np.array((2,3,4,5,6,5,5,7,5,4))
print(x)
print(type(x))

[2 3 4 5 6 5 5 7 5 4]
<class 'numpy.ndarray'>


In [78]:
#second method to create numpy array
a = np.arange(4)
a

array([0, 1, 2, 3])

In [79]:
a = np.arange(-10,-4,1)
a

array([-10,  -9,  -8,  -7,  -6,  -5])

In [80]:
a = np.arange(-10,-4,-1)
a

array([], dtype=int64)

In [81]:
a = np.arange(10,-4,-20)
a

array([10])

In [82]:
# create the random values  between 0,1
a =np.random.random((4,3))
a

array([[0.43549047, 0.21335778, 0.45508927],
       [0.07533267, 0.7403427 , 0.58778746],
       [0.85154793, 0.74696649, 0.01014066],
       [0.86509587, 0.27229499, 0.24198457]])

In [83]:
# random.randint generates  random integer  first value is limit and second value is size of array
x1 = np.random.randint(50,size = 6)
print(x1)
x2 = np.random.randint(10,size = (3,4,5))
print(x2)
x3 = np.random.randint(10,size = (4,5))
print(x3)

[46 37  5 26 12  9]
[[[5 3 9 9 4]
  [5 9 2 9 3]
  [9 8 9 4 1]
  [0 8 1 0 5]]

 [[1 2 6 8 4]
  [5 2 6 8 5]
  [1 7 7 8 8]
  [7 6 9 0 7]]

 [[8 8 9 4 5]
  [4 4 7 8 1]
  [3 8 2 1 3]
  [8 8 6 1 8]]]
[[9 3 1 9 0]
 [2 0 2 4 3]
 [0 5 8 9 2]
 [9 7 4 9 8]]


In [84]:
## O- D array or scaler array which ha zero dimention
# .ndim  gives the dimention 
arr0 = np.array(42)
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,3]])
print(arr0)
print('Dimention : ',arr0.ndim)
print(arr)
print('Dimention : ',arr.ndim)
print(arr2)
print('Dimention : ',arr2.ndim)
arr3 = np.random.randint(50,size = (3,4,5))
print(arr3)
print('Dimention : ',arr3.ndim)

42
Dimention :  0
[1 2 3 4 5]
Dimention :  1
[[1 2 3]
 [4 5 3]]
Dimention :  2
[[[41 15 47 15 15]
  [41 39 43 34 32]
  [ 4 17 32 25 32]
  [14 33 38 25 44]]

 [[42 26 25 19 24]
  [18  0  9 45 16]
  [37 46  9 46 13]
  [ 0 42 10 14 10]]

 [[15 42 32 24 17]
  [36 12 29 28 40]
  [40 39 42 23 18]
  [ 9 45  7 40  9]]]
Dimention :  3


In [85]:
# accesss or reading of an array 

In [86]:
# reshape method 
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,3,4)
print(arr)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [87]:
print(arr2[1][3])
print(arr2[1,3])
print(arr2[-1,-2])



7
7
10


In [88]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,4,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [90]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
print(arr2[0,:])

[0 1 2 3]


In [92]:
print(arr2[:,0])

[0 4 8]


In [93]:
print(arr2[1:,1:])

[[ 5  6  7]
 [ 9 10 11]]


In [94]:
print(arr2[::2,0:2:])#([row,column])

[[0 1]
 [8 9]]


In [95]:
print(arr2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [96]:
print(arr2[-1: : -2, ::-3])

[[11  8]
 [ 3  0]]


In [97]:
print(arr2[1::2,1::])

[[5 6 7]]


In [98]:
# slicing in 3d array
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [99]:
print(arr3[1,1::2,::2])


[[15 17]
 [21 23]]


In [100]:
print(arr3[0], end = '\n\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



In [101]:
print(arr3[0,0])

[0 1 2]


In [102]:
print(arr3[1,:3], end= "\n\n")

[[12 13 14]
 [15 16 17]
 [18 19 20]]



In [103]:
print(arr3[0, :2,::2])

[[0 2]
 [3 5]]


In [104]:
a1 = np.array([1,2,3,4])
a2 = np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)
print(a2.dtype)

int64
float64


In [105]:
print(a1.itemsize)
print(a2.itemsize)

8
8


In [106]:
print(a1.nbytes)
print(a2.nbytes)

32
32


In [107]:
a1 = np.array([1,2,3,4])
a2 = np.array([[1,2,3,4],[5,6,7,8]])
#ndim shows dimention
print(a1.ndim)
print(a2.ndim)

1
2


In [108]:
#shape
print(a1.shape)
print(a2.shape)

(4,)
(2, 4)


In [109]:
#size 
print(a1.size)
print(a2.size)


4
8


In [110]:
# zeros create array of 0s
print(np.zeros(10))
print(np.zeros((3,6)))
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [111]:
print(np.ones(10))
print(np.ones((3,6)))
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [112]:
# identity function
np.identity(4) # default value as float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
a1= np.array([1,2,3,4])
b1 = np.array([5,6,7,8])
print(a1,b1)

[1 2 3 4] [5 6 7 8]


In [114]:
print(a1+5)
print(a1-5)
print(a1*2)
print(a1/2)
print(a1//2)
print(-a1)
print(a1**2)
print(a1%2)

[6 7 8 9]
[-4 -3 -2 -1]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[-1 -2 -3 -4]
[ 1  4  9 16]
[1 0 1 0]


In [115]:
print(a1+b1)
print(a1-b1)
print(a1 * b1)
print(a1  /b1)
print(a1  // b1)
print(a1 ** b1)
print(a1 %b1)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[    1    64  2187 65536]
[1 2 3 4]


In [116]:
arr1 = np.array([9,10,20])
arr2 = np.array([2,5,7])
np.dot(arr1,arr2)

np.int64(208)

In [119]:
x = np.arange(50).reshape(10,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
np.mean(x)
y = np.mean(x,axis = 0) # mean of specific column
z = np.mean(x,axis = 1) # mean of specific row
print(y,z)

[22.5 23.5 24.5 25.5 26.5] [ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]


In [128]:
print(np.average(x))
print(np.average(x,axis = 0))
print(np.average(x,axis = 1))

24.5
[22.5 23.5 24.5 25.5 26.5]
[ 2.  7. 12. 17. 22. 27. 32. 37. 42. 47.]


In [129]:
np.min(x)

np.int64(0)

In [131]:
np.min(x, axis = 0)

array([0, 1, 2, 3, 4])

In [132]:
np.min(x,axis = 1)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [130]:
np.max(x)

np.int64(49)

In [133]:
np.max(x,axis=0)

array([45, 46, 47, 48, 49])

In [134]:
np.max(x,axis= 1)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [136]:
np.var(x) # variance  

np.float64(208.25)

In [137]:
np.var(x,axis= 0)

array([206.25, 206.25, 206.25, 206.25, 206.25])

In [138]:
np.var(x,axis= 1)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [139]:
np.sum(x)

np.int64(1225)

In [140]:
np.sum(x,axis = 0)

array([225, 235, 245, 255, 265])

In [141]:
np.sum(x,axis = 1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

In [143]:
p25 = np.percentile(x,25)
p50 = np.percentile(x,50)
p75 = np.percentile(x,75)
p100 = np.percentile(x,100)
print('25th percentile ' , p25)
print('50th percentile ' , p50)
print('75th percentile ' , p75)
print('100th percentile ' , p100)

25th percentile  12.25
50th percentile  24.5
75th percentile  36.75
100th percentile  49.0


In [145]:
a1 = np.array([2,4,5,7,8,1,5,6])
for i in a1:
    print(i)

2
4
5
7
8
1
5
6


In [147]:
a2 = np.arange(20).reshape(4,5)
for i in a2:
    print(i,end = '\n')

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [149]:
a3 = np.arange(20).reshape(5,2,2)
for i in a3:
    print(i,end = '\n\n')

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[ 8  9]
 [10 11]]

[[12 13]
 [14 15]]

[[16 17]
 [18 19]]



## stacking 

In [153]:
s1 = np.arange(12).reshape(3,4)
s2 = np.arange(12,24).reshape(3,4)
print(s1) 
print(s2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [155]:
s3 = np.hstack((s1,s2))
## horizantal join
s3

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [159]:
s4 = np.vstack((s1,s2)) # vertical join
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [160]:
## spliting 

In [166]:
# horizantal  hsplit me vertical cut perform hoga
s5 = np.hsplit(s3,2)
s5
s6 = np.hsplit(s3,4)
s6

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [170]:
# vertical  vsplit me horizantal cut perform hoga
s7 = np.vsplit(s4,2)
print(s7)
s8  = np.vsplit(s4,3)
s8

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [171]:
# if there is unequal division in the argument this will show error 