In [ ]:
import numpy as np
import pandas as pd


In [ ]:
# wap to which sustract the mean of each row from a matrix 
matrix = np.arange(9).reshape(3,3)
print(matrix)
row_mean = np.mean(matrix, axis = 1)
result = matrix - row_mean
print(result)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


In [21]:
# q2 Q2. Write a python program to count the number of elements in 2D array. 
#Test case: Input: np.array([1, 2])
# Expected Output: 2
a = np.arange(20).reshape(4,5)
b = (a.size)
print(b)


20


In [40]:
'''
Q3. You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float. 
Test Case: Input: 1 2 3 4 5 6 7 8 Expected Output: [8.0 7.0 6.0 5.0 4.0 3.0 2.0 1.0]'''
#a = list(input('enter the list of numbers '))
m = np.arange(8)
a = m.astype(float)
print(a[::-1])



[7. 6. 5. 4. 3. 2. 1. 0.]


In [54]:
#'''Q5. Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a, b) as parameter to function. 
#Input: a = 4 b = 4 
#Expected Output:
#[[1,1,1,1],
#[1,0,0,1], 
#[1,0,0,1],
#1,1,1,1]]
def bodered_array(a,b):
    if a <=1 or b <=1:
        return np.ones(a,b)
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr

c = bodered_array(4,4)
print(c)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Q7. Write a program which makes an array having corresponding max value out of two given arrays. 
#Input:
# a=np.array([6,3,1,5,8])
# b=np.array([3,2,1,7,2])
# Output: [6 3 1 7 8]
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c = np.maximum(a,b)
print(c)


[6 3 1 7 8]


In [ ]:
'''
Q8. Write a python function that accepts infinite number of numpy arrays and do the 
vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error. 
Test Case: Input: a= [[0 1 2 3 4] [5 6 7 8 9]] 
b= [[1 1 1 1 1] [1 1 1 1 1]] 
Output:
 [[0 1 2 3 4] 
[5 6 7 8 9] 
[1 1 1 1 1]
 [1 1 1 1 1]]

'''
a= np.array([[0, 1, 2, 3 ,4], [5, 6, 7, 8, 9]]) 
b= np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]) 
c= np.vstack((a,b))
print(c)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [72]:
'''Q 9. Write a python program to replace multiples of 3 or 5 as 0 in the given
array.
Input: arr=[1 2 3 4 5 6 7 9]
Expected Output: [1 2 0 4 0 0 7 0]
'''
arr = np.array([1,2,3,4,5,6,7,8,9])
index = [2,4,5,8]
arr[index] = 0 
arr
        
        

array([1, 2, 0, 4, 0, 0, 7, 8, 0])

In [ ]:
# Q.10  Solve the given  problem using fancy Indexing:
#1. Double the array elements at given indexes
#Given:
#arr = np.arrange(10)
#indexes = [0,3,4,9]
#Expected Output: [ 0 1 2 6 8 5 6 7 8 18]

arr = np.array([1,2,3,4,5,6,7,8,9])
index = [2,3,4,8]
arr[index] *= 2
arr


array([ 1,  2,  6,  8, 10,  6,  7,  8, 18])

In [ ]:
'''
Q.11 Using a given array make a different array as in below example
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
• Internal repeation should be as length of the array.
'''
arr = np.array([1,2,3])
